public class Exce{
	 
	 public static void main(String args[])
	 {
		 int num=5;
		 int result, data=0;
		 try
		 {
			result =num/data; 
         }
		 catch(Exception e)
		 {
			 System.out.println(e);
		 }
		 finally 
		 {
			 System.out.println("code is axcuted");
		 }
		 }
	 }
		 